cask_args appdir: '/Applications'
tap 'caskroom/cask'
tap 'caskroom/versions'
tap 'getantibody/tap'

# Install Java as a prereq
cask 'java'
brew 'ansible'
brew 'antibody'
brew 'coreutils'
brew 'editorconfig'
brew 'elixir'
brew 'findutils'
brew 'gnu-tar'
brew 'gnu-sed'
brew 'gawk'
brew 'gnutls'
brew 'gnu-indent'
brew 'gnu-getopt'
brew 'hub'
brew 'libyaml'
brew 'jq'
brew 'ksonnet/tap/ks'
brew 'mas'
brew 'nodejs'
brew 'openssl'
brew 'tmux'
brew 'tig'
brew 'tree'
brew 'vim'
brew 'wget'

cask '1password'
cask 'alfred'
cask 'atom'
cask 'dash'
cask 'dropbox-beta'
cask 'firefox'
cask 'keybase'
cask 'gitter'
cask 'google-chrome'
cask 'google-cloud-sdk'
cask 'iterm2'
cask 'slack'
cask 'skype'
cask 'spotify'
cask 'vagrant'

mas 'Cinch', id: 412529613
mas 'DaisyDisk', id: 411643860
mas 'Microsoft Remote Desktop', id: 129503466
mas 'Pixelmator', id: 407963104
