# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh
source $HOME/.zsh/zsh-options.zsh
plugins=(git brew httpie)
source $ZSH/oh-my-zsh.sh

source $HOME/.zsh/aliases.zsh
source $HOME/.zsh/exports.zsh

# Setup spaceship prompt
fpath=(/usr/local/share/zsh/site-functions $fpath)
autoload -U compinit && compinit
autoload -U promptinit; promptinit
prompt spaceship

# Enable asdf version manager
test -e $HOME/.asdf/asdf.sh && source $HOME/.asdf/asdf.sh
test -e $HOME/.asdf/completions/asdf.bash && source $HOME/.asdf/completions/asdf.bash

# Source local zsh customizations
[ -s ~/.zshrc.local ] && source ~/.zshrc.local
